module.exports = {
    inputUsername: '#username',
    inputPassword: '#password',
    btnSubmit: 'button[type="submit"]',
    addElement: '//*[@onclick="addElement()"]',
    deleteElement: '//*[@onclick="deleteElement()"]',
    checkbox: '//*[@type="checkbox"]',
    dropdown: '//*[@id="dropdown"]',
    cdombutton: '//*[@class="large-2 columns"]//a[1]',
    cdomvalue: '//*[@id="canvas"]',
    dragdropvalue1: '//*[@id="column-a"]',
    dragdropvalue2: '//*[@id="column-b"]',
    dragdropvalue3: '//*[@id="columns"]//div[1]',
    dynamicControlCheckbox: '//*[@type="checkbox"]',
    dynamicControlremoveButton: '//*[text()="Remove"]',
    dynamicControlmessage1: '//*[@id="message"]',
    dynamicControladdButton: '//*[text()="Add"]',
    dynamicControlmessage2: '//*[@id="message"]',
    dynamicControlenableBuuton: '//*[text()="Enable"]',
    dynamicControlmessage3: '//*[@id="message"]',
    dynamicControlinputBox: '//*[@type="text"]',
    dynamicControldisableButton: '//*[text()="Disable"]',
    dynamicControlmessage4: '//*[@id="message"]',
    entryaddLink: '//*[@id="restart-ad"]',
    entryad: '//*[@class="modal"]',
    entryaddclosebutton: '//*[text()="Close"]',
    iframeselectbold: '//*[@title="Bold"]',
    iframealligncenter: '//*[@title="Align center"]',
    geolocation: '//*[@onclick="getLocation()"]',
    jsAlert: '//*[@onclick="jsAlert()"]',
    jsConfirm: '//*[@onclick="jsConfirm()"]',
    jsPrompt: '//*[@onclick="jsPrompt()"]',
    Alertresult: '//*[@id="result"]',
    keypressresult: '//*[@id="result"]',
    inputs: '//*[@type="number"]',
    newWindowlink: '//*[text()="Click Here"]',
    notificmsglink: '//*[text()="Click here"]',
    notificmsgresult: '//*[contains(text(),"Action")]'
}